<a href="https://colab.research.google.com/github/SarinaMashreghi/ML-notebooks/blob/main/tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
scalar = tf.constant([2,2])
print(scalar.shape)
scalar.ndim

(2,)


1

In [ ]:
v = tf.Variable([2])
s = tf.constant([2])
v[0].assign(7)
v

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([7], dtype=int32)>

In [ ]:
# random tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(2)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1012345 , -0.2744976 ],
        [ 1.4204658 ,  1.2609464 ],
        [-0.43640924, -1.9633987 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# shuffle 

not_shuffled = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [ ]:
ones = tf.ones([1,2])
ones

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [ ]:
# numpy to tensorflow

import numpy as np
numpy_A = np.arange(1,25)
tf_A = tf.constant(numpy_A, shape = (2,3,4))
numpy_A, tf_A, tf.size(tf_A)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
tf_A[1:, :, :1]

<tf.Tensor: shape=(1, 3, 1), dtype=int64, numpy=
array([[[13],
        [17],
        [21]]])>

In [ ]:
d2_tensor = tf.zeros([2, 2])
d2_tensor[-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
# add extra dimension
# d2_tensor = d2_tensor[...,tf.newaxis]  
d2_tensor 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
tf.expand_dims(d2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>


##Matrix multiplication




In [ ]:
tensor = tf.constant([[1,2],
                     [3,4]])
tf.matmul(tensor,tensor), tensor @ tensor, tensor *tensor # element-wise

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [15, 22]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [15, 22]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 1,  4],
        [ 9, 16]], dtype=int32)>)

In [ ]:
t1 = tf.constant([[1,2],
                  [3,4],
                  [5,6]])
t2 = tf.constant([[1,2],
                  [3,4],
                  [5,6]])
reshape = tf.reshape(t2, [2,3])
transpose = tf.transpose(t2)

t2, reshape, transpose

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [ ]:
tf.matmul(t1, reshape), tf.matmul(t1, transpose)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]], dtype=int32)>)

**Changing percision**

In [ ]:
A = tf.constant([1.5, 2.5])
A = tf.cast(A, dtype = tf.float16)
A

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 2.5], dtype=float16)>

###Aggregating tensors

In [ ]:
# absolute values

B = tf.constant([-1,-2])
tf.abs(B) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
C = tf.constant(np.random.randint(0,100, size=30))
C

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([22, 67, 66, 56, 19,  5, 93, 25, 74, 92, 99, 51, 70,  2,  7, 46, 68,
       45,  2, 69, 89, 64, 50, 54, 35, 57, 98, 41, 58, 64])>

In [ ]:
tf.reduce_min(C), tf.reduce_max(C), tf.reduce_mean(C), tf.reduce_sum(C)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=52>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1588>)

In [ ]:
C[tf.argmax(C)]

<tf.Tensor: shape=(), dtype=int64, numpy=99>

###Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
D = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
D

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
D_squeezed = tf.squeeze(D)
D_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

###One-hot encoding

In [ ]:
list_1 = [0,1,2,3,4]
depth = 5
tf.one_hot(list_1,depth, on_value=2)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2]], dtype=int32)>

###Math operations

In [ ]:
E = tf.range(1,10)
E

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
E = tf.cast(E, dtype=np.float32)
tf.sqrt(E), tf.math.log(E)

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>)

###Tensors and Numpy

In [ ]:
F = tf.constant(np.array([1,2,3]))
F, np.array(F), type(np.array(F)), F.numpy()

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>,
 array([1, 2, 3]),
 numpy.ndarray,
 array([1, 2, 3]))