<a href="https://colab.research.google.com/github/SarinaMashreghi/ML-notebooks/blob/main/data%20generation/VAE_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data generation


In [9]:
from sklearn.datasets import make_regression, make_classification

X, y = make_classification(n_samples=100,
                        n_features=20,
                           n_informative=10,
                           n_classes=4)
X, y

(array([[ 9.56026431e-01,  1.11353588e+00,  1.16329341e+00, ...,
         -4.60752997e-01, -9.58555629e-01, -2.24053180e+00],
        [ 8.36867260e-01, -1.14065178e+00,  7.12763695e-02, ...,
         -1.12269217e+00,  2.56194465e-01, -2.18001063e+00],
        [-3.95924240e-01, -5.00736531e-01,  2.87249774e+00, ...,
          1.27538025e+00, -8.89485495e-01, -3.54438604e+00],
        ...,
        [ 1.22518968e+00,  4.92629879e-02, -1.52668251e+00, ...,
          3.52499337e-01,  1.12419374e-01, -2.50525757e-01],
        [ 6.68530916e-02,  2.06905546e+00, -2.21178357e+00, ...,
         -1.18523539e+00,  8.72286081e-01,  1.35183616e+00],
        [ 3.52605393e-03, -2.81841432e-01, -2.98360150e+00, ...,
         -6.72803790e-01,  2.01940780e-01, -4.62577108e-02]]),
 array([3, 0, 0, 1, 0, 3, 1, 0, 0, 3, 2, 0, 0, 2, 2, 1, 0, 0, 3, 0, 1, 3,
        1, 3, 2, 3, 2, 2, 1, 3, 2, 2, 0, 1, 1, 3, 3, 0, 0, 2, 2, 2, 1, 2,
        0, 2, 3, 0, 2, 3, 3, 1, 2, 3, 2, 2, 1, 2, 2, 3, 3, 2, 0, 1, 1, 0,
       

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[ 9.03343450e-01,  1.19734321e+00,  7.58212566e-01, ...,
        -4.61652306e-01, -1.17718977e+00, -1.01547305e+00],
       [ 7.88681896e-01, -1.33750666e+00,  2.23855320e-01, ...,
        -1.11754180e+00,  1.54139591e-01, -9.88168872e-01],
       [-3.97578360e-01, -6.17917460e-01,  1.59457837e+00, ...,
         1.25861387e+00, -1.10149099e+00, -1.60370814e+00],
       ...,
       [ 1.16234724e+00,  5.60863726e-04, -5.58074696e-01, ...,
         3.44167460e-01, -3.43355864e-03, -1.17679927e-01],
       [ 4.77316180e-02,  2.27183169e+00, -8.93315540e-01, ...,
        -1.17951343e+00,  8.29357367e-01,  6.05227185e-01],
       [-1.32051649e-02, -3.71768382e-01, -1.27098959e+00, ...,
        -6.71765100e-01,  9.46791938e-02, -2.55242022e-02]])

##VAE

In [13]:
from keras import backend as K
import tensorflow as tf

latent_dim = 10
sample_dim = X.shape[1]

class Sampling(tf.keras.layers.Layer):
  def call(self, inputs):
   mean, log_var = inputs
   return K.random_normal(tf.shape(log_var)) * K.exp(log_var / 2)+mean

In [19]:
from tensorflow.keras.layers import *
K.clear_session()

inputs = Input(shape=(sample_dim,))
x = Dense(64, activation="relu")(inputs)
x = Dense(32, activation="relu")(x)

latent_mean = Dense(latent_dim)(x)
latent_var = Dense(latent_dim)(x)

sampling = Sampling()([latent_mean, latent_var])

encoder = tf.keras.models.Model(inputs=inputs, outputs=sampling, name="encoder")

decoder_input = encoder(inputs)
x = Dense(32, activation="relu")(decoder_input)
x = Dense(64, activation="relu")(x)
outputs = Dense(sample_dim, "tanh")(x)

decoder = tf.keras.models.Model(inputs=decoder_input, outputs=outputs, name="decoder")

vae = tf.keras.models.Model(inputs=inputs, outputs=outputs, name="VAE")

In [20]:
encoder.summary()

Model: "encoder"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 20)]         0           []                               
                                                                                                  
 dense (Dense)                  (None, 64)           1344        ['input_1[0][0]']                
                                                                                                  
 dense_1 (Dense)                (None, 32)           2080        ['dense[0][0]']                  
                                                                                                  
 dense_2 (Dense)                (None, 10)           330         ['dense_1[0][0]']                
                                                                                            

In [21]:
decoder.summary()

Model: "decoder"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10)]              0         
                                                                 
 dense_4 (Dense)             (None, 32)                352       
                                                                 
 dense_5 (Dense)             (None, 64)                2112      
                                                                 
 dense_6 (Dense)             (None, 20)                1300      
                                                                 
Total params: 3,764
Trainable params: 3,764
Non-trainable params: 0
_________________________________________________________________


In [22]:
vae.summary()

Model: "VAE"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 20)]              0         
                                                                 
 encoder (Functional)        (None, 10)                4084      
                                                                 
 dense_4 (Dense)             (None, 32)                352       
                                                                 
 dense_5 (Dense)             (None, 64)                2112      
                                                                 
 dense_6 (Dense)             (None, 20)                1300      
                                                                 
Total params: 7,848
Trainable params: 7,848
Non-trainable params: 0
_________________________________________________________________


In [23]:
vae.compile(loss="mse", optimizer="adam", metrics=["mse"])

vae.fit(X, X, epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 5ms/step - loss: 1.0763 - mse: 1.0763
Epoch 2/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0882 - mse: 1.0882
Epoch 3/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0344 - mse: 1.0344
Epoch 4/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0314 - mse: 1.0314
Epoch 5/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0180 - mse: 1.0180
Epoch 6/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0196 - mse: 1.0196
Epoch 7/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0107 - mse: 1.0107
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 0.9854 - mse: 0.9854
Epoch 9/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0019 - mse: 1.0019
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 0.9881 - mse: 0.9881
